### ISSUE TITLE
proxies fail on node < 6

### ISSUE THREAD

**Issue by harlantwood** [GravityNetwork/distributedjs#3]
ask Jorge if we care about node < 6

eg:

```
  1) Compiler Environment setup It should rewrite global variable declarations to act on the global object:
     Error: proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag
      at new global.Proxy (node_modules/harmony-reflect/reflect.js:2158:13)
      at Object.proxify (node_modules/chai/lib/chai/utils/proxify.js:36:10)
      at new Assertion (node_modules/chai/lib/chai/assertion.js:68:17)
      at chai.expect (node_modules/chai/lib/chai/interface/expect.js:9:12)
      at Context.<anonymous> (test/CompilerSpec.js:20:5)
```

-- from https://travis-ci.org/GravityNetwork/distributedjs/jobs/270268082

**Comment by harlantwood** [comment]
`make sure to pass the --harmony_proxies flag` when running tests
